### ISSUE TITLE
付费后，如果获取博客的内容呢？

### ISSUE THREAD

**Issue by yinhaibo** [UlordChain/ulord-blog-demo#1]
通过付费接口可以获得一个文件哈希，如何才能获得文件内容呢？

**Comment by LittleSecretary** [comment]
@yinhaibo  在获取到文件哈希后，需要调用ipfs api来获取到文件内容。要与api交互，您需要运行一个本地守护进程 windows守护进程下载 [https://dist.ipfs.io/#go-ipfs](url)，在安装完守护进程后，
在您的html页面中引入CDN

> <script src="https://unpkg.com/ipfs-api/dist/index.js"></script>

然后在js输入

> var ipfs = window.IpfsApi('localhost', '5001')

最后调用ifps获取文件接口 

> ipfs.files.get(yourhash,function
> (err,files) {
>   if (err || typeof files == "undefined") {
>     console.log(err);
>   } else {
>     console.log(files);
>   }
> })

**Comment by yinhaibo** [comment]
好，知道了，谢谢。
